name: Deploy site to web server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: .github/playbook.yml
        inventoryFile: .github/inventory
        keyFile: ".github/key.pem"
        keyFileVaultPass: ${{ secrets.KEYFILE_VAULT_PASS }}
        extraVars: "-e ansible_user=github -e ansible_become=true -e ansible_become_pass=${{ secrets.SSH_PASSWORD }} -e local_dir=${{ github.workspace }}"
        verbosity: vv
