name: Deploy site to web server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: .github/playbook.yml
        inventoryFile: .github/inventory
        verbosity: vv
